spring.application.name=pfeaccdemie
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe
spring.datasource.username=postgres
spring.datasource.password=yamin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A46
jwt.expiration=86400000

# Admin par defaut
admin.email=admin@academie.com
admin.password=Admin@123
admin.nom=Administrateur
admin.prenom=System

# Configuration Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contact.academiesportif@gmail.com
spring.mail.password=rmvynlibceysouot
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend.url=http://localhost:4200





